export const LOGIN_DATA = 'LOGIN_DATA';
export const PET_LIST ='PET_LIST';
export const COUNTRY_LIST = 'COUNTRY_LIST'
export const STATE_LIST ='STATE_LIST';
export const CITY_LIST ='CITY_LIST';
export const CATEGORY_LIST = 'CATEGORY_LIST';
export const BREED_LIST ='BREED_LIST';
export const ALL_POSTS ='ALL_POSTS';
export const ALLPETS_CATEGORY ='ALLPETS_CATEGORY';
export const USER_DATA ='USER_DATA';
export const DISTANCE ='DISTANCE';
export const POSTS_BY_PETID = 'POSTS_BY_PETID';
export const POSTS_COMMENTS= 'POSTS_COMMENTS';
export const LOGIN_PET= 'LOGIN_PET';
export const PET_DETAILS='PET_DETAILS';
export const MATING_LIST='MATING_LIST';
export const VACCINATION_LIST='VACCINATION_LIST';
export const CHARTS_FILES_LIST ="CHARTS_FILES_LIST";
export const FRIENDS_REQUESTS ="FRIENDS_REQUESTS";
export const FRIENDS_LISTS = "FRIENDS_LISTS";
export const CHAT_DATA = "CHAT_DATA";
export const CHAT_LISTING ="CHAT_LISTING";
export const ADOPT_LIST ="ADOPT_LIST";
export const PRODUCT_CATEGORIES ="PRODUCT_CATEGORIES";



