export const LOGIN_DATA = 'LOGIN_DATA';
export const MY_INFO = 'MY_INFO';
export const MANAGER_INFO = 'MANAGER_INFO';
export const CLIENT_LIST = 'CLIENT_LIST';
export const CLIENT_DETAIL = 'CLIENT_DETAIL';
export const GET_PAYMENT_LIST = 'GET_PAYMENT_LIST';
export const DASHBOARD_LIST = 'DASHBOARD_LIST';
export const DASHBOARD_MESSAGE_LIST = 'DASHBOARD_MESSAGE_LIST';
